# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

obj-$(CONFIG_USB_LSTP) += lstp.o
lstp-y := lstp-main.o lstp-spi.o lstp-gpio.o lstp-i2c.o lstp-ipmi.o lstp-uart.o \
	lstp-mmio.o
