/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (C) 2025 ARM Ltd.
 */

#ifndef __ASM_RHI_H_
#define __ASM_RHI_H_

#include <linux/types.h>

#define SMC_RHI_CALL(func)				\
	ARM_SMCCC_CALL_VAL(ARM_SMCCC_FAST_CALL,		\
			   ARM_SMCCC_SMC_64,		\
			   ARM_SMCCC_OWNER_STANDARD_HYP,\
			   (func))

#define RHI_DA_SUCCESS				0x0
#define RHI_DA_ERROR_INCOMPLETE			0x1
#define RHI_DA_ERROR_DATA_NOT_AVAILABLE		0x2
#define RHI_DA_ERROR_INVALID_VDEV_ID		0x3
#define RHI_DA_ERROR_INVALID_OBJECT		0x4
#define RHI_DA_ERROR_INPUT			0x5
#define RHI_DA_ERROR_DEVICE			0x6
#define RHI_DA_ERROR_INVALID_OFFSET		0x7
#define RHI_DA_ERROR_ACCESS_FAILED		0x8
#define RHI_DA_ERROR_BUSY			0x9
#define RHI_DA_ABORTED_OPERATION_HAD_COMPLETED	0xA

#define RHI_DA_FEATURE_OBJECT_SIZE		BIT(0)
#define RHI_DA_FEATURE_OBJECT_READ		BIT(1)
#define RHI_DA_FEATURE_VDEV_CONTINUE		BIT(2)
#define RHI_DA_FEATURE_VDEV_GET_MEASUREMENT	BIT(3)
#define RHI_DA_FEATURE_VDEV_GET_INTF_REPORT	BIT(4)
#define RHI_DA_FEATURE_VDEV_SET_TDI_STATE	BIT(5)

#define RHI_DA_BASE_FEATURE	(RHI_DA_FEATURE_OBJECT_SIZE |		\
				 RHI_DA_FEATURE_OBJECT_READ |		\
				 RHI_DA_FEATURE_VDEV_GET_INTF_REPORT |	\
				 RHI_DA_FEATURE_VDEV_GET_MEASUREMENT |	\
				 RHI_DA_FEATURE_VDEV_SET_TDI_STATE)
#define RHI_DA_FEATURES			SMC_RHI_CALL(0x004B)

#define RHI_DA_VDEV_CONTINUE		SMC_RHI_CALL(0x0051)
#define RHI_DA_VDEV_GET_INTERFACE_REPORT SMC_RHI_CALL(0x0052)

#define RHI_VDEV_MEASURE_SIGNED		BIT(0)
#define RHI_VDEV_MEASURE_RAW		BIT(1)
#define RHI_VDEV_MEASURE_EXCHANGE	BIT(2)
struct rhi_vdev_measurement_params {
	union {
		u64 flags;
		u8 padding0[256];
	};
	union {
		u8 indices[32];
		u8 padding1[256];
	};
	union {
		u8 nonce[32];
		u8 padding2[256];
	};
};
#define RHI_DA_VDEV_GET_MEASUREMENTS	SMC_RHI_CALL(0x0053)

enum rhi_tdi_state {
	RHI_DA_TDI_CONFIG_UNLOCKED,
	RHI_DA_TDI_CONFIG_LOCKED,
	RHI_DA_TDI_CONFIG_RUN,
};
#define RHI_DA_VDEV_SET_TDI_STATE	SMC_RHI_CALL(0x0054)
#define RHI_DA_VDEV_ABORT		SMC_RHI_CALL(0x0056)

#endif
