# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_SAMPLE_DEVSEC) += devsec_common.o
devsec_common-y := common.o

obj-$(CONFIG_SAMPLE_DEVSEC) += devsec_bus.o
devsec_bus-y := bus.o

obj-$(CONFIG_SAMPLE_DEVSEC) += devsec_link_tsm.o
devsec_link_tsm-y := link_tsm.o
