#!/bin/bash -eu

. debian/debian.env

# Ovveride default GCC version to the default in Noble
GCC="gcc-13"

# Override options in rules.d/hooks.mk (normally master does not have this
# file but it got added for generic annotations enforcement. Must replace the
# file, otherwise it continues to grow.
cat <<EOD >"${DEBIAN}/rules.d/hooks.mk"
do_tools_common		= false
do_tools_host		= false
do_tools_noble_hwe	= true
do_lib_rust		= true
gcc			= $GCC
rustc			= rustc-1.82
rustfmt			= /usr/lib/rust-1.82/bin/rustfmt
bindgen			= bindgen-0.65
EOD

#
# Re-enable producing linux-modules-extra for backwards compatibility.
#
for i in amd64 arm64 ppc64el s390x; do
	echo "do_extras_package = true" >>${DEBIAN}/rules.d/${i}.mk
done

