name: Kernel Build

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: ${{ matrix.arch == 'amd64' && 'x86_64' || 'ARM64' }} - ${{ matrix.flavour }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            arch: amd64
            flavour: nvidia
          - runs-on: ubuntu-24.04-arm
            arch: arm64
            flavour: nvidia
          - runs-on: ubuntu-24.04-arm
            arch: arm64
            flavour: nvidia-64k
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Free Disk Space
        # Reference: https://github.com/actions/runner-images/issues/2840
        run: |
          echo "Available disk space before cleanup:"
          df -h
          # Remove unnecessary packages
          sudo apt-get remove -y '^aspnetcore-.*' || true
          sudo apt-get remove -y '^dotnet-.*' || true
          sudo apt-get remove -y '^llvm-.*' || true
          sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri || true
          # Remove Docker images and containers
          docker rmi $(docker images -q) || true
          docker system prune -a -f || true
          # Remove large directories
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          # Clean package cache
          sudo apt-get autoremove -y
          sudo apt-get autoclean
          sudo apt-get clean
          echo "Available disk space after cleanup:"
          df -h

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev python3 libdw-dev

      - name: Configure Kernel
        run: |
          debian/scripts/misc/annotations --arch ${{ matrix.arch }} --flavour ${{ matrix.flavour }} --export > .config
          make oldconfig
          # Ensure WERROR is disabled
          ./scripts/config --disable CONFIG_WERROR
          # Disable certificate verification
          ./scripts/config --disable SYSTEM_TRUSTED_KEYS
          ./scripts/config --disable SYSTEM_REVOCATION_KEYS ""

      - name: Build Kernel
        run: |
          make -j$(nproc)